package io.buedchen.server.Storage;

public interface SqlStatements {

    String DROP_CHANNELS_TABLE = "DROP TABLE IF EXISTS CHANNELS";
    String CREATE_CHANNELS_TABLE = "CREATE TABLE CHANNELS(CHANNEL_ID varchar(20), CHANNEL_DESC varchar(200))";
    String INSERT_CHANNEL_VALUES = "INSERT INTO CHANNELS VALUES (?,?)";
    String DROP_CONTENTS_TABLE = "DROP TABLE IF EXISTS CONTENTS";
    String CREATE_CONTENTS_TABLE =
            "create table CONTENTS( CHANNEL_ID varchar(30), URL varchar(255), SHOWTIME INTEGER, TITLE varchar(100))";
    String INSERT_CONTENTS_VALUES = "INSERT INTO CONTENTS VALUES (?, ?, ?, ?)";
    String DROP_CLIENTS_TABLE = "DROP TABLE IF EXISTS CLIENTS";
    String CREATE_CLIENTS_TABLE = "create table CLIENTS(CLIENT_ID varchar(30), CHANNEL_ID varchar(20))";
    String INSERT_CLIENTS_VALUES = "INSERT INTO CLIENTS VALUES ( ?, ?)";
    String DROP_PROJECTS_TABLE = "DROP TABLE IF EXISTS PROJECTS";
    String CREATE_PROJECTS_TABLE = "create table PROJECTS(PROJECT_ID varchar(20), PROJECT_DESC varchar(200))";
    String INSERT_PROJECT_VALUES = "INSERT INTO PROJECTS VALUES ( ?, ? )";
    String DROP_DASHBOARDS_TABLE = "DROP TABLE IF EXISTS DASHBOARDS";
    String CREATE_DASHBOARDS_TABLE =
            "create table DASHBOARDS( PROJECT_ID varchar(30), URL varchar(255), DASHBOARD_DESC varchar(255), TITLE varchar(100))";
    String INSERT_DASHBOARD_VALUES = "INSERT INTO DASHBOARDS VALUES ( ?, ?, ?, ?)";
    String DELETE_FROM_CONTENTS = "DELETE FROM CONTENTS WHERE CHANNEL_ID = ? AND URL = ?";
    String CHECK_IF_CLIENT_PRESENT = "SELECT * from CLIENTS WHERE CLIENT_ID = ?";
    String UPDATE_CHANNEL_FOR_CLIENT = "UPDATE CLIENTS SET CHANNEL_ID = ? WHERE CLIENT_ID = ?";
    String CREATE_CLIENT = "INSERT INTO CLIENTS (CLIENT_ID, CHANNEL_ID) VALUES ( ?, ?)";
    String DELETE_CHANNEL = "DELETE FROM CHANNELS WHERE CHANNEL_ID = ?";
    String UPDATE_CHANNEL = "UPDATE CHANNELS SET CHANNEL_DESC = ? WHERE CHANNEL_ID = ?";
    String CHANNEL_CONTENT_UPDATED =
            "UPDATE CONTENTS SET SHOWTIME = ? WHERE CHANNEL_ID = ? AND URL = ?";
    String CREATE_PROJECT = "INSERT INTO PROJECTS (PROJECT_ID, PROJECT_DESC) VALUES ( ?, ?)";
    String UPDATE_PROJECT = "UPDATE PROJECTS SET PROJECT_DESC = ? WHERE PROJECT_ID = ?";
    String REMOVE_PROJECT = "DELETE FROM PROJECTS WHERE PROJECT_ID = ?";
    String PROJECT_DASHBOARD_UPDATED =
            "UPDATE DASHBOARDS SET DASHBOARD_DESC = ?, TITLE = ? WHERE PROJECT_ID = ? AND URL = ?";
    String PROJECT_DASHBOARD_REMOVED = "DELETE FROM DASHBOARDS WHERE PROJECT_ID = ? AND URL = ?";

}
